services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      GOOGLE_FORM_ACTION_URL: ${GOOGLE_FORM_ACTION_URL}
      GOOGLE_FORM_ENTRY_EMAIL: ${GOOGLE_FORM_ENTRY_EMAIL}
      GOOGLE_FORM_ENTRY_ISSUE: ${GOOGLE_FORM_ENTRY_ISSUE}
      GOOGLE_FORM_ENTRY_TYPE: ${GOOGLE_FORM_ENTRY_TYPE}
      NEXT_PUBLIC_URMS_EXTENSION_DEV_IDS: ${NEXT_PUBLIC_URMS_EXTENSION_DEV_IDS}
    restart: unless-stopped
